/* eslint-disable */
// This file is generated by FDDP. Do not edit by hand.
// protocolVersion: v9
// contractVersion: contract_demo_gorm_v1

import { queryFromFields } from "@fddp/next-sdk";

export const fields = { "global": { "config": { "appName": "global.config.appName" } }, "me": { "profile": { "description": "me.profile.description", "id": "me.profile.id", "name": "me.profile.name" } } } as const;

export const resources = { "project": { "list": "project.list" } } as const;

export const resourceCallers = { "project": { "list": (query: FddpGeneratedCollectionQuery<"project.list"> = {}): import("@fddp/next-sdk").FddpCollectionDescriptor => ({ $type: "collection", args: { first: query.first, after: query.after, filter: query.filter, orderBy: query.orderBy }, selection: { fields: query.fields, expand: query.expand } }) } } as const;

function buildFddpGeneratedQuery(input: FddpGeneratedLoadQuery): import("@fddp/next-sdk").FddpQuery {
  const query = (input.fields?.length ? queryFromFields(input.fields) : {}) as Record<string, any>;
  if (input.projectList) {
    query["project"] ??= {};
    query["project"]["list"] = resourceCallers["project"]["list"](input.projectList);
  }
  return query as import("@fddp/next-sdk").FddpQuery;
}

export const queryCallers = { query: (client: import("@fddp/next-sdk").FddpClient, query: import("@fddp/next-sdk").FddpQuery, options?: import("@fddp/next-sdk").FddpQueryOptions) => client.query<FddpGeneratedQueryData>(query, options), load: (client: import("@fddp/next-sdk").FddpClient, input: FddpGeneratedLoadQuery, options?: import("@fddp/next-sdk").FddpQueryOptions) => client.query<FddpGeneratedQueryData>(buildFddpGeneratedQuery(input), options), resource: { "project": { "list": (client: import("@fddp/next-sdk").FddpClient, query: FddpGeneratedCollectionQuery<"project.list"> = {}, options?: import("@fddp/next-sdk").FddpQueryOptions) => client.query<FddpGeneratedResourceData<"project.list">>({ "project": { "list": resourceCallers["project"]["list"](query) } }, options) } } } as const;

export function createFddpApi(client: import("@fddp/next-sdk").FddpClient) {
  return { query: (query: import("@fddp/next-sdk").FddpQuery, options?: import("@fddp/next-sdk").FddpQueryOptions) => queryCallers.query(client, query, options), load: (input: FddpGeneratedLoadQuery, options?: import("@fddp/next-sdk").FddpQueryOptions) => queryCallers.load(client, input, options), resource: { "project": { "list": (query: FddpGeneratedCollectionQuery<"project.list"> = {}, options?: import("@fddp/next-sdk").FddpQueryOptions) => queryCallers.resource["project"]["list"](client, query, options) } }, command: { "user": { "profile": { "update": (input: FddpGeneratedCommandInput<"user.profile.update">, options?: import("@fddp/next-sdk").FddpCommandOptions) => commandCallers["user"]["profile"]["update"](client, input, options) } } } } as const;
}

export const commands = { "user": { "profile": { "update": "user.profile.update" } } } as const;

export const commandCallers = { "user": { "profile": { "update": (client: import("@fddp/next-sdk").FddpClient, input: FddpGeneratedCommandInput<"user.profile.update">, options?: import("@fddp/next-sdk").FddpCommandOptions) => client.command<unknown, FddpGeneratedCommandInput<"user.profile.update">>("user.profile.update", input, options) } } } as const;

export type FddpGeneratedData = {
  global: {
    config: {
      appName: string;
    };
  };
  me: {
    profile: {
      description: string;
      id: string;
      name: string;
    };
  };
};

export type FddpGeneratedField = "global.config.appName" | "me.profile.description" | "me.profile.id" | "me.profile.name";
export type FddpGeneratedResource = "project.list";
export type FddpGeneratedCommand = "user.profile.update";
export type FddpGeneratedResourceItem<TResource extends FddpGeneratedResource> = FddpGeneratedResourceItemMap[TResource];
export type FddpGeneratedResourceResult<TResource extends FddpGeneratedResource> = FddpGeneratedCollectionResult<FddpGeneratedResourceItem<TResource>>;
export type FddpGeneratedResourceData<TResource extends FddpGeneratedResource> = FddpGeneratedResourceDataMap[TResource];
export type FddpGeneratedQueryData = FddpGeneratedData & FddpGeneratedAllResourceData;
export type FddpGeneratedLoadQuery = {
  fields?: readonly FddpGeneratedField[];
  projectList?: FddpGeneratedCollectionQuery<"project.list">;
};
export type FddpGeneratedResourceField<TResource extends FddpGeneratedResource> = FddpGeneratedResourceFieldMap[TResource];
export type FddpGeneratedResourceFilter<TResource extends FddpGeneratedResource> = Partial<Record<FddpGeneratedResourceField<TResource>, import("@fddp/next-sdk").FddpFilterValue>>;
export type FddpGeneratedResourceOrderBy<TResource extends FddpGeneratedResource> = { field: FddpGeneratedResourceField<TResource>; direction?: "asc" | "desc" };
export type FddpGeneratedResourceRelation<TResource extends FddpGeneratedResource> = keyof FddpGeneratedResourceRelationFieldMap[TResource] & string;
export type FddpGeneratedResourceRelationField<TResource extends FddpGeneratedResource, TRelation extends FddpGeneratedResourceRelation<TResource>> = FddpGeneratedResourceRelationFieldMap[TResource][TRelation];
export type FddpGeneratedResourceExpand<TResource extends FddpGeneratedResource> = {
  readonly [TRelation in FddpGeneratedResourceRelation<TResource>]?: readonly FddpGeneratedResourceRelationField<TResource, TRelation>[];
};
export type FddpGeneratedCollectionQuery<TResource extends FddpGeneratedResource> = Omit<import("@fddp/next-sdk").FddpCollectionArgs, "filter" | "orderBy"> & {
  fields?: readonly FddpGeneratedResourceField<TResource>[];
  filter?: FddpGeneratedResourceFilter<TResource>;
  orderBy?: readonly FddpGeneratedResourceOrderBy<TResource>[];
  expand?: FddpGeneratedResourceExpand<TResource>;
};
type FddpGeneratedResourceFieldMap = {
  "project.list": "id" | "name" | "ownerId" | "status" | "updatedAt";
};
type FddpGeneratedResourceRelationFieldMap = {
  "project.list": {
    "owner": "id" | "name";
  };
};
type FddpGeneratedResourceItemMap = {
  "project.list": {
    id?: string;
    name?: string;
    ownerId?: string;
    status?: string;
    updatedAt?: string;
    owner?: {
      id: string;
      name: string;
    };
  };
};
type FddpGeneratedResourceDataMap = {
  "project.list": {
  project: {
    list: FddpGeneratedCollectionResult<FddpGeneratedResourceItem<"project.list">>;
  };
};
};
type FddpGeneratedAllResourceData = {
  project: {
    list: FddpGeneratedCollectionResult<FddpGeneratedResourceItem<"project.list">>;
  };
};
export type FddpGeneratedCommandInput<TCommand extends FddpGeneratedCommand> = {
  "user.profile.update": {
  displayName: string;
};
}[TCommand];

export type FddpGeneratedCollectionResult<TItem = unknown> = {
  items: TItem[];
  pageInfo?: { hasNextPage: boolean; hasPreviousPage?: boolean; startCursor?: string; endCursor?: string };
  totalCount?: number | null;
};
