export type FddpContractField = {
  field: string;
  type: "string" | "number" | "boolean" | "object" | "unknown" | string;
  owner?: string;
  permission?: string;
  nullable?: boolean;
  deprecated?: boolean;
  sensitivity?: string;
  cacheScope?: string;
};

export type FddpContractResource = {
  path: string;
  owner?: string;
  permission?: string;
  types?: readonly string[];
  maxPageSize?: number;
  deprecated?: boolean;
  fields?: readonly FddpContractResourceField[];
  relations?: readonly FddpContractResourceRelation[];
};

export type FddpContractResourceField = {
  field: string;
  type: "string" | "number" | "boolean" | "object" | "unknown" | string;
  nullable?: boolean;
  filterable?: boolean;
  orderable?: boolean;
};

export type FddpContractResourceRelation = {
  name: string;
  fields?: readonly FddpContractResourceField[];
};

export type FddpContractCommand = {
  name: string;
  owner?: string;
  permission?: string;
  idempotencyRequired?: boolean;
  auditLevel?: string;
  input?: readonly FddpContractInputField[];
};

export type FddpContractInputField = {
  field: string;
  type: "string" | "number" | "boolean" | "object" | "unknown" | string;
  required?: boolean;
  nullable?: boolean;
};

export type FddpContractSchema = {
  protocolVersion?: string;
  contractVersion?: string;
  fields: readonly FddpContractField[];
  resources?: readonly FddpContractResource[];
  commands?: readonly FddpContractCommand[];
};

export type FddpTypegenOptions = {
  dataTypeName?: string;
  fieldsConstName?: string;
  resourcesConstName?: string;
  commandsConstName?: string;
};

export type FddpContractChangeSeverity = "breaking" | "non-breaking";

export type FddpContractChange = {
  severity: FddpContractChangeSeverity;
  path: string;
  message: string;
};

export type FddpContractDiff = {
  breaking: FddpContractChange[];
  nonBreaking: FddpContractChange[];
};

export type FddpContractDiffOptions = {
  allowRequiredCommandInputAdd?: boolean;
  allowCommandInputRequiredTighten?: boolean;
  allowIdempotencyTighten?: boolean;
  allowResourceMaxPageSizeDecrease?: boolean;
};

type TreeNode = {
  children: Map<string, TreeNode>;
  field?: FddpContractField;
};

type ResourceTreeNode = {
  children: Map<string, ResourceTreeNode>;
  resource?: FddpContractResource;
};

export function generateFddpTypes(schema: FddpContractSchema, options: FddpTypegenOptions = {}): string {
  validateFddpContractSchema(schema);
  const dataTypeName = options.dataTypeName ?? "FddpGeneratedData";
  const fieldsConstName = options.fieldsConstName ?? "fields";
  const resourcesConstName = options.resourcesConstName ?? "resources";
  const commandsConstName = options.commandsConstName ?? "commands";
  const root = buildTree(schema.fields);
  const resources = schema.resources ?? [];
  const commands = schema.commands ?? [];

  return [
    "/* eslint-disable */",
    "// This file is generated by FDDP. Do not edit by hand.",
    schema.protocolVersion ? `// protocolVersion: ${schema.protocolVersion}` : undefined,
    schema.contractVersion ? `// contractVersion: ${schema.contractVersion}` : undefined,
    "",
    `import { queryFromFields } from "@fddp/next-sdk";`,
    "",
    `export const ${fieldsConstName} = ${renderFieldConstants(root)} as const;`,
    "",
    `export const ${resourcesConstName} = ${renderPathConstants(resources.map((resource) => resource.path))} as const;`,
    "",
    `export const resourceCallers = ${renderResourceCallers(resources)} as const;`,
    "",
    `function buildFddpGeneratedQuery(input: FddpGeneratedLoadQuery): import("@fddp/next-sdk").FddpQuery {`,
    `  const query = (input.fields?.length ? queryFromFields(input.fields) : {}) as Record<string, any>;`,
    ...renderLoadQueryBuilderLines(resources),
    `  return query as import("@fddp/next-sdk").FddpQuery;`,
    `}`,
    "",
    `export const queryCallers = ${renderQueryCallers(resources)} as const;`,
    "",
    `export function createFddpApi(client: import("@fddp/next-sdk").FddpClient) {`,
    `  return ${renderBoundFddpApi(resources, commands)} as const;`,
    `}`,
    "",
    `export const ${commandsConstName} = ${renderPathConstants(commands.map((command) => command.name))} as const;`,
    "",
    `export const commandCallers = ${renderCommandCallers(commands)} as const;`,
    "",
    `export type ${dataTypeName} = ${renderType(root, 0)};`,
    "",
    `export type FddpGeneratedField = ${renderStringUnion(schema.fields.map((field) => field.field))};`,
    `export type FddpGeneratedResource = ${renderStringUnion(resources.map((resource) => resource.path))};`,
    `export type FddpGeneratedCommand = ${renderStringUnion(commands.map((command) => command.name))};`,
    `export type FddpGeneratedResourceItem<TResource extends FddpGeneratedResource> = FddpGeneratedResourceItemMap[TResource];`,
    `export type FddpGeneratedResourceResult<TResource extends FddpGeneratedResource> = FddpGeneratedCollectionResult<FddpGeneratedResourceItem<TResource>>;`,
    `export type FddpGeneratedResourceData<TResource extends FddpGeneratedResource> = FddpGeneratedResourceDataMap[TResource];`,
    `export type FddpGeneratedQueryData = ${dataTypeName} & FddpGeneratedAllResourceData;`,
    `export type FddpGeneratedLoadQuery = {`,
    `  fields?: readonly FddpGeneratedField[];`,
    ...renderLoadQueryResourceFields(resources),
    `};`,
    `export type FddpGeneratedResourceField<TResource extends FddpGeneratedResource> = FddpGeneratedResourceFieldMap[TResource];`,
    `export type FddpGeneratedResourceFilter<TResource extends FddpGeneratedResource> = Partial<Record<FddpGeneratedResourceField<TResource>, import("@fddp/next-sdk").FddpFilterValue>>;`,
    `export type FddpGeneratedResourceOrderBy<TResource extends FddpGeneratedResource> = { field: FddpGeneratedResourceField<TResource>; direction?: "asc" | "desc" };`,
    `export type FddpGeneratedResourceRelation<TResource extends FddpGeneratedResource> = keyof FddpGeneratedResourceRelationFieldMap[TResource] & string;`,
    `export type FddpGeneratedResourceRelationField<TResource extends FddpGeneratedResource, TRelation extends FddpGeneratedResourceRelation<TResource>> = FddpGeneratedResourceRelationFieldMap[TResource][TRelation];`,
    `export type FddpGeneratedResourceExpand<TResource extends FddpGeneratedResource> = {`,
    `  readonly [TRelation in FddpGeneratedResourceRelation<TResource>]?: readonly FddpGeneratedResourceRelationField<TResource, TRelation>[];`,
    `};`,
    `export type FddpGeneratedCollectionQuery<TResource extends FddpGeneratedResource> = Omit<import("@fddp/next-sdk").FddpCollectionArgs, "filter" | "orderBy"> & {`,
    `  fields?: readonly FddpGeneratedResourceField<TResource>[];`,
    `  filter?: FddpGeneratedResourceFilter<TResource>;`,
    `  orderBy?: readonly FddpGeneratedResourceOrderBy<TResource>[];`,
    `  expand?: FddpGeneratedResourceExpand<TResource>;`,
    `};`,
    `type FddpGeneratedResourceFieldMap = ${renderResourceFieldMap(resources)};`,
    `type FddpGeneratedResourceRelationFieldMap = ${renderResourceRelationFieldMap(resources)};`,
    `type FddpGeneratedResourceItemMap = ${renderResourceItemMap(resources)};`,
    `type FddpGeneratedResourceDataMap = ${renderResourceDataMap(resources)};`,
    `type FddpGeneratedAllResourceData = ${renderAllResourceDataType(resources)};`,
    `export type FddpGeneratedCommandInput<TCommand extends FddpGeneratedCommand> = ${renderCommandInputMap(commands)}[TCommand];`,
    "",
    `export type FddpGeneratedCollectionResult<TItem = unknown> = {`,
    `  items: TItem[];`,
    `  pageInfo?: { hasNextPage: boolean; hasPreviousPage?: boolean; startCursor?: string; endCursor?: string };`,
    `  totalCount?: number | null;`,
    `};`,
    ""
  ].filter((line): line is string => line !== undefined).join("\n");
}

export function validateFddpContractSchema(schema: FddpContractSchema): void {
  if (!schema || typeof schema !== "object" || !Array.isArray(schema.fields)) {
    throw new Error("Invalid FDDP contract: expected an object with a fields array.");
  }

  const seen = new Set<string>();
  for (const field of schema.fields) {
    if (!field || typeof field.field !== "string" || field.field.trim() === "") {
      throw new Error("Invalid FDDP contract: every field needs a non-empty field path.");
    }
    if (seen.has(field.field)) {
      throw new Error(`Invalid FDDP contract: duplicate field ${field.field}.`);
    }
    seen.add(field.field);
  }

  validateNamedPaths(schema.resources ?? [], "resource", (resource) => resource.path);
  validateNamedPaths(schema.commands ?? [], "command", (command) => command.name);

  for (const resource of schema.resources ?? []) {
    validateNamedPaths(resource.fields ?? [], `resource field for ${resource.path}`, (field) => field.field);
    validateNamedPaths(resource.relations ?? [], `resource relation for ${resource.path}`, (relation) => relation.name);
    for (const relation of resource.relations ?? []) {
      validateNamedPaths(relation.fields ?? [], `resource relation field for ${resource.path}.${relation.name}`, (field) => field.field);
    }
  }
}

export function diffFddpContracts(previous: FddpContractSchema, next: FddpContractSchema, options: FddpContractDiffOptions = {}): FddpContractDiff {
  validateFddpContractSchema(previous);
  validateFddpContractSchema(next);

  const breaking: FddpContractChange[] = [];
  const nonBreaking: FddpContractChange[] = [];
  const addBreaking = (path: string, message: string) => breaking.push({ severity: "breaking", path, message });
  const addNonBreaking = (path: string, message: string) => nonBreaking.push({ severity: "non-breaking", path, message });

  diffNamedItems(
    "field",
    byKey(previous.fields, (field) => field.field),
    byKey(next.fields, (field) => field.field),
    addBreaking,
    addNonBreaking,
    compareContractField
  );

  diffNamedItems(
    "resource",
    byKey(previous.resources ?? [], (resource) => resource.path),
    byKey(next.resources ?? [], (resource) => resource.path),
    addBreaking,
    addNonBreaking,
    (path, previousResource, nextResource, breaking, nonBreaking) => compareContractResource(path, previousResource, nextResource, options, breaking, nonBreaking)
  );

  diffNamedItems(
    "command",
    byKey(previous.commands ?? [], (command) => command.name),
    byKey(next.commands ?? [], (command) => command.name),
    addBreaking,
    addNonBreaking,
    (path, previousCommand, nextCommand, breaking, nonBreaking) => compareContractCommand(path, previousCommand, nextCommand, options, breaking, nonBreaking)
  );

  return { breaking, nonBreaking };
}

function buildTree(fields: readonly FddpContractField[]): TreeNode {
  const root = node();

  for (const field of fields) {
    const parts = field.field.split(".").filter(Boolean);
    if (parts.length === 0) {
      continue;
    }

    let current = root;
    for (const part of parts) {
      let next = current.children.get(part);
      if (!next) {
        next = node();
        current.children.set(part, next);
      }
      current = next;
    }
    current.field = field;
  }

  return root;
}

function node(): TreeNode {
  return { children: new Map() };
}

function resourceNode(): ResourceTreeNode {
  return { children: new Map() };
}

function renderFieldConstants(root: TreeNode): string {
  return renderConstNode(root, []);
}

function renderPathConstants(paths: readonly string[]): string {
  if (paths.length === 0) {
    return "{}";
  }
  const root = node();
  for (const path of paths) {
    const parts = path.split(".").filter(Boolean);
    if (parts.length === 0) {
      continue;
    }
    let current = root;
    for (const part of parts) {
      let next = current.children.get(part);
      if (!next) {
        next = node();
        current.children.set(part, next);
      }
      current = next;
    }
    current.field = { field: path, type: "string" };
  }
  return renderConstNode(root, []);
}

function renderCommandCallers(commands: readonly FddpContractCommand[]): string {
  if (commands.length === 0) {
    return "{}";
  }
  const root = node();
  for (const command of commands) {
    const parts = command.name.split(".").filter(Boolean);
    let current = root;
    for (const part of parts) {
      let next = current.children.get(part);
      if (!next) {
        next = node();
        current.children.set(part, next);
      }
      current = next;
    }
    current.field = { field: command.name, type: "string" };
  }
  return renderCommandCallerNode(root, []);
}

function renderResourceCallers(resources: readonly FddpContractResource[]): string {
  if (resources.length === 0) {
    return "{}";
  }
  const root = node();
  for (const resource of resources) {
    const parts = resource.path.split(".").filter(Boolean);
    let current = root;
    for (const part of parts) {
      let next = current.children.get(part);
      if (!next) {
        next = node();
        current.children.set(part, next);
      }
      current = next;
    }
    current.field = { field: resource.path, type: "string" };
  }
  return renderResourceCallerNode(root, []);
}

function renderQueryCallers(resources: readonly FddpContractResource[]): string {
  return `{ query: (client: import("@fddp/next-sdk").FddpClient, query: import("@fddp/next-sdk").FddpQuery, options?: import("@fddp/next-sdk").FddpQueryOptions) => client.query<FddpGeneratedQueryData>(query, options), load: (client: import("@fddp/next-sdk").FddpClient, input: FddpGeneratedLoadQuery, options?: import("@fddp/next-sdk").FddpQueryOptions) => client.query<FddpGeneratedQueryData>(buildFddpGeneratedQuery(input), options), resource: ${renderResourceQueryCallers(resources)} }`;
}

function renderBoundFddpApi(
  resources: readonly FddpContractResource[],
  commands: readonly FddpContractCommand[]
): string {
  return `{ query: (query: import("@fddp/next-sdk").FddpQuery, options?: import("@fddp/next-sdk").FddpQueryOptions) => queryCallers.query(client, query, options), load: (input: FddpGeneratedLoadQuery, options?: import("@fddp/next-sdk").FddpQueryOptions) => queryCallers.load(client, input, options), resource: ${renderBoundResourceQueryCallers(resources)}, command: ${renderBoundCommandCallers(commands)} }`;
}

function renderResourceQueryCallers(resources: readonly FddpContractResource[]): string {
  if (resources.length === 0) {
    return "{}";
  }
  const root = resourceNode();
  for (const resource of resources) {
    const parts = resource.path.split(".").filter(Boolean);
    let current = root;
    for (const part of parts) {
      let next = current.children.get(part);
      if (!next) {
        next = resourceNode();
        current.children.set(part, next);
      }
      current = next;
    }
    current.resource = resource;
  }
  return renderResourceQueryCallerNode(root, []);
}

function renderResourceQueryCallerNode(current: ResourceTreeNode, path: string[]): string {
  if (current.children.size === 0 && current.resource) {
    const resourceName = current.resource.path;
    const resourceType = JSON.stringify(resourceName);
    const queryObject = renderSingleResourceQueryObject(resourceName);
    return `(client: import("@fddp/next-sdk").FddpClient, query: FddpGeneratedCollectionQuery<${resourceType}> = {}, options?: import("@fddp/next-sdk").FddpQueryOptions) => client.query<FddpGeneratedResourceData<${resourceType}>>(${queryObject}, options)`;
  }

  const entries = Array.from(current.children.entries()).sort(([a], [b]) => a.localeCompare(b)).map(([key, child]) => {
    return `${JSON.stringify(key)}: ${renderResourceQueryCallerNode(child, [...path, key])}`;
  });
  return `{ ${entries.join(", ")} }`;
}

function renderBoundResourceQueryCallers(resources: readonly FddpContractResource[]): string {
  if (resources.length === 0) {
    return "{}";
  }
  const root = resourceNode();
  for (const resource of resources) {
    const parts = resource.path.split(".").filter(Boolean);
    let current = root;
    for (const part of parts) {
      let next = current.children.get(part);
      if (!next) {
        next = resourceNode();
        current.children.set(part, next);
      }
      current = next;
    }
    current.resource = resource;
  }
  return renderBoundResourceQueryCallerNode(root, []);
}

function renderBoundResourceQueryCallerNode(current: ResourceTreeNode, path: string[]): string {
  if (current.children.size === 0 && current.resource) {
    const resourceName = current.resource.path;
    const resourceType = JSON.stringify(resourceName);
    const access = current.resource.path.split(".").filter(Boolean).map((part) => `[${JSON.stringify(part)}]`).join("");
    return `(query: FddpGeneratedCollectionQuery<${resourceType}> = {}, options?: import("@fddp/next-sdk").FddpQueryOptions) => queryCallers.resource${access}(client, query, options)`;
  }

  const entries = Array.from(current.children.entries()).sort(([a], [b]) => a.localeCompare(b)).map(([key, child]) => {
    return `${JSON.stringify(key)}: ${renderBoundResourceQueryCallerNode(child, [...path, key])}`;
  });
  return `{ ${entries.join(", ")} }`;
}

function renderBoundCommandCallers(commands: readonly FddpContractCommand[]): string {
  if (commands.length === 0) {
    return "{}";
  }
  const root = node();
  for (const command of commands) {
    const parts = command.name.split(".").filter(Boolean);
    let current = root;
    for (const part of parts) {
      let next = current.children.get(part);
      if (!next) {
        next = node();
        current.children.set(part, next);
      }
      current = next;
    }
    current.field = { field: command.name, type: "string" };
  }
  return renderBoundCommandCallerNode(root, []);
}

function renderBoundCommandCallerNode(current: TreeNode, path: string[]): string {
  if (current.children.size === 0) {
    const commandName = path.join(".");
    const commandType = JSON.stringify(commandName);
    const access = path.map((part) => `[${JSON.stringify(part)}]`).join("");
    return `(input: FddpGeneratedCommandInput<${commandType}>, options?: import("@fddp/next-sdk").FddpCommandOptions) => commandCallers${access}(client, input, options)`;
  }

  const entries = sortedEntries(current.children).map(([key, child]) => {
    return `${JSON.stringify(key)}: ${renderBoundCommandCallerNode(child, [...path, key])}`;
  });
  return `{ ${entries.join(", ")} }`;
}

function renderSingleResourceQueryObject(resourcePath: string): string {
  const parts = resourcePath.split(".").filter(Boolean);
  if (parts.length === 0) {
    return "{}";
  }
  let out = "resourceCallers";
  for (const part of parts) {
    out += `[${JSON.stringify(part)}]`;
  }
  const descriptor = `${out}(query)`;
  let current = descriptor;
  for (let index = parts.length - 1; index >= 0; index--) {
    current = `{ ${JSON.stringify(parts[index])}: ${current} }`;
  }
  return current;
}

function renderLoadQueryResourceFields(resources: readonly FddpContractResource[]): string[] {
  return [...resources].sort((a, b) => a.path.localeCompare(b.path)).map((resource) => {
    return `  ${loadQueryKey(resource.path)}?: FddpGeneratedCollectionQuery<${JSON.stringify(resource.path)}>;`;
  });
}

function renderLoadQueryBuilderLines(resources: readonly FddpContractResource[]): string[] {
  return [...resources].sort((a, b) => a.path.localeCompare(b.path)).flatMap((resource) => {
    const key = loadQueryKey(resource.path);
    const parts = resource.path.split(".").filter(Boolean);
    if (parts.length === 0) {
      return [];
    }
    const lines = [`  if (input.${key}) {`];
    let current = "query";
    for (let index = 0; index < parts.length - 1; index++) {
      const part = JSON.stringify(parts[index]);
      lines.push(`    ${current}[${part}] ??= {};`);
      current = `${current}[${part}]`;
    }
    const leaf = JSON.stringify(parts[parts.length - 1]);
    lines.push(`    ${current}[${leaf}] = resourceCallers${parts.map((part) => `[${JSON.stringify(part)}]`).join("")}(input.${key});`);
    lines.push(`  }`);
    return lines;
  });
}

function loadQueryKey(path: string): string {
  const parts = path.split(".").filter(Boolean);
  if (parts.length === 0) {
    return "resource";
  }
  const [first, ...rest] = parts;
  return first + rest.map((part) => {
    const chars = Array.from(part);
    if (chars.length === 0) {
      return "";
    }
    return chars[0]!.toUpperCase() + chars.slice(1).join("");
  }).join("");
}

function renderResourceCallerNode(current: TreeNode, path: string[]): string {
  if (current.children.size === 0) {
    const resourceName = path.join(".");
    const resourceType = JSON.stringify(resourceName);
    return `(query: FddpGeneratedCollectionQuery<${resourceType}> = {}): import("@fddp/next-sdk").FddpCollectionDescriptor => ({ $type: "collection", args: { first: query.first, after: query.after, filter: query.filter, orderBy: query.orderBy }, selection: { fields: query.fields, expand: query.expand } })`;
  }

  const entries = sortedEntries(current.children).map(([key, child]) => {
    return `${JSON.stringify(key)}: ${renderResourceCallerNode(child, [...path, key])}`;
  });
  return `{ ${entries.join(", ")} }`;
}

function renderCommandCallerNode(current: TreeNode, path: string[]): string {
  if (current.children.size === 0) {
    const commandName = path.join(".");
    const commandType = JSON.stringify(commandName);
    return `(client: import("@fddp/next-sdk").FddpClient, input: FddpGeneratedCommandInput<${commandType}>, options?: import("@fddp/next-sdk").FddpCommandOptions) => client.command<unknown, FddpGeneratedCommandInput<${commandType}>>(${commandType}, input, options)`;
  }

  const entries = sortedEntries(current.children).map(([key, child]) => {
    return `${JSON.stringify(key)}: ${renderCommandCallerNode(child, [...path, key])}`;
  });
  return `{ ${entries.join(", ")} }`;
}

function renderCommandInputMap(commands: readonly FddpContractCommand[]): string {
  const sorted = [...commands].sort((a, b) => a.name.localeCompare(b.name));
  if (sorted.length === 0) {
    return "Record<never, never>";
  }
  const lines = sorted.map((command) => {
    return `  ${JSON.stringify(command.name)}: ${renderInputType(command.input ?? [])};`;
  });
  return ["{", ...lines, "}"].join("\n");
}

function renderInputType(fields: readonly FddpContractInputField[]): string {
  if (fields.length === 0) {
    return "Record<string, unknown>";
  }
  const lines = [...fields].sort((a, b) => a.field.localeCompare(b.field)).map((field) => {
    const optional = field.required ? "" : "?";
    return `  ${safePropertyName(field.field)}${optional}: ${inputTsType(field)};`;
  });
  return ["{", ...lines, "}"].join("\n");
}

function renderResourceFieldMap(resources: readonly FddpContractResource[]): string {
  const sorted = [...resources].sort((a, b) => a.path.localeCompare(b.path));
  if (sorted.length === 0) {
    return "Record<never, never>";
  }
  const lines = sorted.map((resource) => {
    return `  ${JSON.stringify(resource.path)}: ${renderResourceFieldUnion(resource.fields ?? [])};`;
  });
  return ["{", ...lines, "}"].join("\n");
}

function renderResourceRelationFieldMap(resources: readonly FddpContractResource[]): string {
  const sorted = [...resources].sort((a, b) => a.path.localeCompare(b.path));
  if (sorted.length === 0) {
    return "Record<never, never>";
  }
  const lines = sorted.map((resource) => {
    return `  ${JSON.stringify(resource.path)}: ${renderRelationFieldObject(resource.relations ?? [])};`;
  });
  return ["{", ...lines, "}"].join("\n");
}

function renderResourceItemMap(resources: readonly FddpContractResource[]): string {
  const sorted = [...resources].sort((a, b) => a.path.localeCompare(b.path));
  if (sorted.length === 0) {
    return "Record<never, never>";
  }
  const lines = sorted.map((resource) => {
    return `  ${JSON.stringify(resource.path)}: ${renderResourceItemType(resource)};`;
  });
  return ["{", ...lines, "}"].join("\n");
}

function renderResourceDataMap(resources: readonly FddpContractResource[]): string {
  const sorted = [...resources].sort((a, b) => a.path.localeCompare(b.path));
  if (sorted.length === 0) {
    return "Record<never, never>";
  }
  const lines = sorted.map((resource) => {
    return `  ${JSON.stringify(resource.path)}: ${renderResourceDataType(resource)};`;
  });
  return ["{", ...lines, "}"].join("\n");
}

function renderAllResourceDataType(resources: readonly FddpContractResource[]): string {
  if (resources.length === 0) {
    return "{}";
  }
  return renderResourceDataTree(resources);
}

function renderResourceDataType(resource: FddpContractResource): string {
  return renderResourceDataTree([resource]);
}

function renderResourceDataTree(resources: readonly FddpContractResource[]): string {
  const root = resourceNode();
  for (const resource of resources) {
    const parts = resource.path.split(".").filter(Boolean);
    let current = root;
    for (const part of parts) {
      let next = current.children.get(part);
      if (!next) {
        next = resourceNode();
        current.children.set(part, next);
      }
      current = next;
    }
    current.resource = resource;
  }
  return renderResourceDataNode(root, 0);
}

function renderResourceDataNode(current: ResourceTreeNode, depth: number): string {
  if (current.children.size === 0) {
    if (!current.resource) {
      return "unknown";
    }
    return `FddpGeneratedCollectionResult<FddpGeneratedResourceItem<${JSON.stringify(current.resource.path)}>>`;
  }

  const indent = "  ".repeat(depth);
  const childIndent = "  ".repeat(depth + 1);
  const lines = Array.from(current.children.entries()).sort(([a], [b]) => a.localeCompare(b)).map(([key, child]) => {
    return `${childIndent}${safePropertyName(key)}: ${renderResourceDataNode(child, depth + 1)};`;
  });
  return ["{", ...lines, `${indent}}`].join("\n");
}

function renderResourceItemType(resource: FddpContractResource): string {
  const fields = resource.fields ?? [];
  const relations = resource.relations ?? [];
  if (fields.length === 0 && relations.length === 0) {
    return "Record<string, unknown>";
  }

  const lines = [
    ...[...fields].sort((a, b) => a.field.localeCompare(b.field)).map((field) => {
      return `    ${safePropertyName(field.field)}?: ${resourceTsType(field)};`;
    }),
    ...[...relations].sort((a, b) => a.name.localeCompare(b.name)).map((relation) => {
      return `    ${safePropertyName(relation.name)}?: ${renderRelationItemType(relation)};`;
    })
  ];
  return ["{", ...lines, "  }"].join("\n");
}

function renderRelationItemType(relation: FddpContractResourceRelation): string {
  const fields = relation.fields ?? [];
  if (fields.length === 0) {
    return "Record<string, unknown>";
  }
  const lines = [...fields].sort((a, b) => a.field.localeCompare(b.field)).map((field) => {
    return `      ${safePropertyName(field.field)}: ${resourceTsType(field)};`;
  });
  return ["{", ...lines, "    }"].join("\n");
}

function renderRelationFieldObject(relations: readonly FddpContractResourceRelation[]): string {
  if (relations.length === 0) {
    return "Record<never, never>";
  }
  const lines = [...relations].sort((a, b) => a.name.localeCompare(b.name)).map((relation) => {
    return `    ${JSON.stringify(relation.name)}: ${renderResourceFieldUnion(relation.fields ?? [])};`;
  });
  return ["{", ...lines, "  }"].join("\n");
}

function renderResourceFieldUnion(fields: readonly FddpContractResourceField[]): string {
  if (fields.length === 0) {
    return "string";
  }
  return renderStringUnion(fields.map((field) => field.field));
}

function renderConstNode(current: TreeNode, path: string[]): string {
  if (current.children.size === 0) {
    return JSON.stringify(path.join("."));
  }

  const entries = sortedEntries(current.children).map(([key, child]) => {
    return `${JSON.stringify(key)}: ${renderConstNode(child, [...path, key])}`;
  });

  return `{ ${entries.join(", ")} }`;
}

function renderType(current: TreeNode, depth: number): string {
  if (current.children.size === 0) {
    return tsType(current.field);
  }

  const indent = "  ".repeat(depth);
  const childIndent = "  ".repeat(depth + 1);
  const lines = sortedEntries(current.children).map(([key, child]) => {
    return `${childIndent}${safePropertyName(key)}: ${renderType(child, depth + 1)};`;
  });

  return ["{", ...lines, `${indent}}`].join("\n");
}

function tsType(field?: FddpContractField): string {
  const base = (() => {
    switch (field?.type) {
      case "string":
        return "string";
      case "number":
        return "number";
      case "boolean":
        return "boolean";
      case "object":
        return "Record<string, unknown>";
      default:
        return "unknown";
    }
  })();

  return field?.nullable ? `${base} | null` : base;
}

function inputTsType(field: FddpContractInputField): string {
  const base = (() => {
    switch (field.type) {
      case "string":
        return "string";
      case "number":
        return "number";
      case "boolean":
        return "boolean";
      case "object":
        return "Record<string, unknown>";
      default:
        return "unknown";
    }
  })();
  return field.nullable ? `${base} | null` : base;
}

function resourceTsType(field: FddpContractResourceField): string {
  const base = (() => {
    switch (field.type) {
      case "string":
        return "string";
      case "number":
        return "number";
      case "boolean":
        return "boolean";
      case "object":
        return "Record<string, unknown>";
      default:
        return "unknown";
    }
  })();
  return field.nullable ? `${base} | null` : base;
}

function sortedEntries(map: Map<string, TreeNode>): Array<[string, TreeNode]> {
  return Array.from(map.entries()).sort(([a], [b]) => a.localeCompare(b));
}

function safePropertyName(key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
}

function renderStringUnion(values: readonly string[]): string {
  const unique = Array.from(new Set(values)).sort((a, b) => a.localeCompare(b));
  if (unique.length === 0) {
    return "never";
  }
  return unique.map((value) => JSON.stringify(value)).join(" | ");
}

function validateNamedPaths<T>(values: readonly T[], label: string, getPath: (value: T) => string): void {
  const seen = new Set<string>();
  for (const value of values) {
    const path = getPath(value);
    if (typeof path !== "string" || path.trim() === "") {
      throw new Error(`Invalid FDDP contract: every ${label} needs a non-empty path.`);
    }
    if (seen.has(path)) {
      throw new Error(`Invalid FDDP contract: duplicate ${label} ${path}.`);
    }
    seen.add(path);
  }
}

function byKey<T>(items: readonly T[], getKey: (item: T) => string): Map<string, T> {
  return new Map(items.map((item) => [getKey(item), item]));
}

function diffNamedItems<T>(
  label: string,
  previous: Map<string, T>,
  next: Map<string, T>,
  addBreaking: (path: string, message: string) => void,
  addNonBreaking: (path: string, message: string) => void,
  compare: (path: string, previous: T, next: T, addBreaking: (path: string, message: string) => void, addNonBreaking: (path: string, message: string) => void) => void
): void {
  for (const [path, previousItem] of previous) {
    const nextItem = next.get(path);
    if (!nextItem) {
      addBreaking(path, `${label} removed`);
      continue;
    }
    compare(path, previousItem, nextItem, addBreaking, addNonBreaking);
  }

  for (const path of next.keys()) {
    if (!previous.has(path)) {
      addNonBreaking(path, `${label} added`);
    }
  }
}

function compareContractField(
  path: string,
  previous: FddpContractField,
  next: FddpContractField,
  addBreaking: (path: string, message: string) => void,
  addNonBreaking: (path: string, message: string) => void
): void {
  compareTypeAndNullability(path, previous, next, addBreaking, addNonBreaking);
  compareDeprecated(path, previous.deprecated, next.deprecated, addNonBreaking);
  compareStringProperty(path, "permission", previous.permission, next.permission, addNonBreaking);
  compareStringProperty(path, "owner", previous.owner, next.owner, addNonBreaking);
  compareStringProperty(path, "cacheScope", previous.cacheScope, next.cacheScope, addNonBreaking);
}

function compareContractResource(
  path: string,
  previous: FddpContractResource,
  next: FddpContractResource,
  options: FddpContractDiffOptions,
  addBreaking: (path: string, message: string) => void,
  addNonBreaking: (path: string, message: string) => void
): void {
  compareDeprecated(path, previous.deprecated, next.deprecated, addNonBreaking);
  compareStringProperty(path, "permission", previous.permission, next.permission, addNonBreaking);
  compareStringProperty(path, "owner", previous.owner, next.owner, addNonBreaking);

  if ((previous.maxPageSize ?? 0) > 0 && (next.maxPageSize ?? previous.maxPageSize ?? 0) > 0 && (next.maxPageSize ?? 0) < (previous.maxPageSize ?? 0)) {
    addByPolicy(options.allowResourceMaxPageSizeDecrease, addBreaking, addNonBreaking, path, `resource maxPageSize decreased from ${previous.maxPageSize} to ${next.maxPageSize}`);
  } else if (previous.maxPageSize !== next.maxPageSize) {
    addNonBreaking(path, `resource maxPageSize changed from ${String(previous.maxPageSize)} to ${String(next.maxPageSize)}`);
  }

  const previousFields = byKey(previous.fields ?? [], (field) => field.field);
  const nextFields = byKey(next.fields ?? [], (field) => field.field);
  diffNamedItems(
    "resource field",
    previousFields,
    nextFields,
    (fieldPath, message) => addBreaking(`${path}.${fieldPath}`, message),
    (fieldPath, message) => addNonBreaking(`${path}.${fieldPath}`, message),
    (fieldPath, previousField, nextField, breaking, nonBreaking) => {
      const fullPath = `${path}.${fieldPath}`;
      compareResourceField(fullPath, previousField, nextField, breaking, nonBreaking);
    }
  );

  const previousRelations = byKey(previous.relations ?? [], (relation) => relation.name);
  const nextRelations = byKey(next.relations ?? [], (relation) => relation.name);
  diffNamedItems(
    "resource relation",
    previousRelations,
    nextRelations,
    (relationPath, message) => addBreaking(`${path}.${relationPath}`, message),
    (relationPath, message) => addNonBreaking(`${path}.${relationPath}`, message),
    (relationPath, previousRelation, nextRelation, breaking, nonBreaking) => {
      const previousRelationFields = byKey(previousRelation.fields ?? [], (field) => field.field);
      const nextRelationFields = byKey(nextRelation.fields ?? [], (field) => field.field);
      diffNamedItems(
        "resource relation field",
        previousRelationFields,
        nextRelationFields,
        (fieldPath, message) => breaking(`${path}.${relationPath}.${fieldPath}`, message),
        (fieldPath, message) => nonBreaking(`${path}.${relationPath}.${fieldPath}`, message),
        (fieldPath, previousField, nextField, relationBreaking, relationNonBreaking) => {
          compareResourceField(`${path}.${relationPath}.${fieldPath}`, previousField, nextField, relationBreaking, relationNonBreaking);
        }
      );
    }
  );
}

function compareResourceField(
  path: string,
  previous: FddpContractResourceField,
  next: FddpContractResourceField,
  addBreaking: (path: string, message: string) => void,
  addNonBreaking: (path: string, message: string) => void
): void {
  compareTypeAndNullability(path, previous, next, addBreaking, addNonBreaking);
  if (previous.filterable && !next.filterable) {
    addBreaking(path, "resource field is no longer filterable");
  } else if (!previous.filterable && next.filterable) {
    addNonBreaking(path, "resource field became filterable");
  }
  if (previous.orderable && !next.orderable) {
    addBreaking(path, "resource field is no longer orderable");
  } else if (!previous.orderable && next.orderable) {
    addNonBreaking(path, "resource field became orderable");
  }
}

function compareContractCommand(
  path: string,
  previous: FddpContractCommand,
  next: FddpContractCommand,
  options: FddpContractDiffOptions,
  addBreaking: (path: string, message: string) => void,
  addNonBreaking: (path: string, message: string) => void
): void {
  compareStringProperty(path, "permission", previous.permission, next.permission, addNonBreaking);
  compareStringProperty(path, "owner", previous.owner, next.owner, addNonBreaking);
  compareStringProperty(path, "auditLevel", previous.auditLevel, next.auditLevel, addNonBreaking);
  if (!previous.idempotencyRequired && next.idempotencyRequired) {
    addByPolicy(options.allowIdempotencyTighten, addBreaking, addNonBreaking, path, "command now requires idempotency key");
  } else if (previous.idempotencyRequired && !next.idempotencyRequired) {
    addNonBreaking(path, "command no longer requires idempotency key");
  }

  const previousInput = byKey(previous.input ?? [], (field) => field.field);
  const nextInput = byKey(next.input ?? [], (field) => field.field);
  diffNamedItems(
    "command input",
    previousInput,
    nextInput,
    (fieldPath, message) => addBreaking(`${path}.${fieldPath}`, message),
    (fieldPath, message) => addNonBreaking(`${path}.${fieldPath}`, message),
    (fieldPath, previousField, nextField, breaking, nonBreaking) => {
      compareCommandInput(`${path}.${fieldPath}`, previousField, nextField, options, breaking, nonBreaking);
    }
  );

  for (const [fieldPath, nextField] of nextInput) {
    if (!previousInput.has(fieldPath) && nextField.required) {
      addByPolicy(options.allowRequiredCommandInputAdd, addBreaking, addNonBreaking, `${path}.${fieldPath}`, "required command input added");
    }
  }
}

function compareCommandInput(
  path: string,
  previous: FddpContractInputField,
  next: FddpContractInputField,
  options: FddpContractDiffOptions,
  addBreaking: (path: string, message: string) => void,
  addNonBreaking: (path: string, message: string) => void
): void {
  compareTypeAndNullability(path, previous, next, addBreaking, addNonBreaking);
  if (!previous.required && next.required) {
    addByPolicy(options.allowCommandInputRequiredTighten, addBreaking, addNonBreaking, path, "command input became required");
  } else if (previous.required && !next.required) {
    addNonBreaking(path, "command input became optional");
  }
}

function addByPolicy(
  allowed: boolean | undefined,
  addBreaking: (path: string, message: string) => void,
  addNonBreaking: (path: string, message: string) => void,
  path: string,
  message: string
): void {
  if (allowed) {
    addNonBreaking(path, `${message} (allowed by diff policy)`);
    return;
  }
  addBreaking(path, message);
}

function compareTypeAndNullability(
  path: string,
  previous: { type: string; nullable?: boolean },
  next: { type: string; nullable?: boolean },
  addBreaking: (path: string, message: string) => void,
  addNonBreaking: (path: string, message: string) => void
): void {
  if (previous.type !== next.type) {
    addBreaking(path, `type changed from ${previous.type} to ${next.type}`);
  }
  if (previous.nullable && !next.nullable) {
    addBreaking(path, "field is no longer nullable");
  } else if (!previous.nullable && next.nullable) {
    addNonBreaking(path, "field became nullable");
  }
}

function compareDeprecated(
  path: string,
  previous: boolean | undefined,
  next: boolean | undefined,
  addNonBreaking: (path: string, message: string) => void
): void {
  if (!previous && next) {
    addNonBreaking(path, "marked deprecated");
  } else if (previous && !next) {
    addNonBreaking(path, "no longer marked deprecated");
  }
}

function compareStringProperty(
  path: string,
  property: string,
  previous: string | undefined,
  next: string | undefined,
  addNonBreaking: (path: string, message: string) => void
): void {
  if (previous !== next) {
    addNonBreaking(path, `${property} changed from ${String(previous)} to ${String(next)}`);
  }
}
